name: Deploy mediasoup to EC2

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feat/ci-cd
    paths:
      - 'apps/server/**'

  pull_request:
    branches:
      - main
    paths:
      - 'apps/server/**'


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build --workspace-root

      - name: Copy build files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          source: |
            apps/server/dist
            apps/server/package.json
            apps/server/pnpm-lock.yaml
          target: /home/ubuntu/project/apps/server

      - name: SSH and install production dependencies + start server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/project/apps/server
            pnpm install --prod
            if pm2 list | grep -q mediasoup; then
              pm2 restart mediasoup
            else
              pm2 start dist/index.js --name mediasoup
            fi
            pm2 save
