name: Deploy mediasoup to EC2

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feat/ci-cd
    paths:
      - 'apps/server/**'

  pull_request:
    branches:
      - main
    paths:
      - 'apps/server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy server files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          source: apps/server/**
          target: /home/ubuntu/server/
          strip_components: 2

      - name: SSH and build/start server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/server
            npm install --legacy-peer-deps
            npm run build
            pm2 restart mediasoup || pm2 start dist/index.js --name mediasoup
