name: Deploy mediasoup to EC2

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feat/ci-cd
    paths:
      - 'apps/server/**'

  pull_request:
    branches:
      - main
    paths:
      - 'apps/server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm
        
      - name: Install dependencies
        run: pnpm install

      - name: Build server only
        run: pnpm turbo run build --filter=server

      - name: Check if dist exists
        run: ls -la apps/server/dist

      - name: Copy build files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          source: apps/server/dist/*
          target: /home/ubuntu/project/apps
          overwrite: true

      - name: SSH and install/start server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/project/apps/server
            if ! command -v pnpm > /dev/null 2>&1; then
              echo "pnpm not found, installing..."
              sudo npm install -g pnpm
            fi
            pnpm install --prod --filter ./apps/server
            if pm2 list | grep -q mediasoup; then
              pm2 restart mediasoup
            else
              pm2 start dist/index.js --name mediasoup
            fi
            pm2 save
